### ISSUE TITLE
sanity checking output_vars

### ISSUE THREAD

**Issue by nicholasmalaya** [grinsfem/grins#207]
Chatting with Roy, we were wishing for a means to sanity check output_vars strings, e.g. "vel_penalty" vs. "velocity_penalty". Any reason not to have this error out when you encounter a string that is not available?

**Comment by nicholasmalaya** [comment]
Even if it does not error out, some sort of warning is probably in order.

Admittedly a low priority option, but one worth mentioning as a nice feature.

**Comment by pbauman** [comment]
I thought that was already happening...

https://github.com/grinsfem/grins/blob/master/src/physics/src/velocity_penalty.C#L91

Maybe I'm not understanding what you're asking?

**Comment by roystgnr** [comment]
Looks like we've still got a bug in #204.  I'm not just getting silent failure to create vel_penalty output when I give the input file the wrong name, I'm getting silent failure to add postprocessed variables in *any* case.  Looking into it now.

**Comment by pbauman** [comment]
Closing this as I believe it was related to #208.
