### ISSUE TITLE
Build error on lonestar with GRINS/master

### ISSUE THREAD

**Issue by nicholasmalaya** [grinsfem/grins#231]
Hi all,

It looks as if some of the new ElasticMembraine class is stepping on gcc 4.4.5's toes...

<pre>
make[2]: Entering directory `/work/00000/npm7/src/grins/build/src'
  CXX      physics/src/physics_factory.lo
In file included from ../../src/physics/include/grins/elastic_membrane.h:29,
                 from ../../src/physics/src/physics_factory.C:61:
../../src/physics/include/grins/elastic_membrane_base.h: In member function 'const libMesh::FEGenericBase<double>* GRINS::ElasticMembraneBase::get_fe(const GRINS::AssemblyContext&)':
../../src/physics/include/grins/elastic_membrane_base.h:69: error: no matching function for call to 'GRINS::AssemblyContext::get_element_fe(GRINS::VariableIndex, int) const'
/work/00000/npm7/LIBRARIES/2015-2-2-libmesh/include/libmesh/fem_context.h:870: note: candidates are: libMesh::FEBase* libMesh::FEMContext::get_element_fe(unsigned int) const
In file included from ../../src/physics/include/grins/elastic_cable.h:30,
                 from ../../src/physics/src/physics_factory.C:62:
../../src/physics/include/grins/elastic_cable_base.h: In member function 'const libMesh::FEGenericBase<double>* GRINS::ElasticCableBase::get_fe(const GRINS::AssemblyContext&)':
../../src/physics/include/grins/elastic_cable_base.h:70: error: no matching function for call to 'GRINS::AssemblyContext::get_element_fe(GRINS::VariableIndex, int) const'
/work/00000/npm7/LIBRARIES/2015-2-2-libmesh/include/libmesh/fem_context.h:870: note: candidates are: libMesh::FEBase* libMesh::FEMContext::get_element_fe(unsigned int) const
make[2]: *** [physics/src/physics_factory.lo] Error 1
make[2]: Leaving directory `/work/00000/npm7/src/grins/build/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/work/00000/npm7/src/grins/build'
make: *** [all] Error 2
</pre>

I'm surprised this is building for everyone else. I'm probing this now on lonestar, but wanted to see if the github hivemind had any quick suggestions.

**Comment by pbauman** [comment]
Pull the latest libmesh and use that. get_element_fe had the API updated. Sorry for the trouble

**Comment by nicholasmalaya** [comment]
Got it-- thanks, we are live. Closing ticket.
