### ISSUE TITLE
output velpen forcing 

### ISSUE THREAD

**Issue by nicholasmalaya** [grinsfem/grins#243]
Hi all,

Right now we can output the normal vectors, but not the forcing, calculated by velocity penalty. This is output as 'vel_penalty_'. It would be great to output the forcing as well. I've got a hacked together version I've been using, so this is not time sensitive. @roystgnr correctly pointed out to me that this is a more general feature that should be officially added to grins and propagated back upstream. 

I'm happy to take a lead on this but I was hoping to get a crash coarse on how one 'officially' adds a variable to available for output. If anyone could point me to a location or commit that did this, I would be happy to poke around with this. I would not expect this to make the 0.6.0 release.

**Comment by pbauman** [comment]
> general feature that should be officially added to grins and propagated back upstream

Upstream = GRINS or upstream = libMesh? If former I understand, if the latter, I don't understand.

> I was hoping to get a crash coarse on how one 'officially' adds a variable to available for output

Everything you need to do should be localized to the Physics subclass from which you want to compute the output. Just append what's there for `VelocityPenalty` already. Namely:

1. Cache an `unsigned int` in the Physics subclass (in this case `VelocityPenalty`) for the local variable number that you get back when registering. For the love of all things holy, initialize it to 0 in the initialization list (see #241).

2. In `VelocityPenalty::register_postprocessing_vars`, check for the variable name that you want to output (whatever you want, that's what will be in the input file to trigger it's output), and register the variable. You pass the string name in to `postprocessing.register_quantity()` and you get back an `unsigned int`, i.e. the cache variable from step 1.

3. In `VelocityPenalty::compute_postprocessed_quantity`, check if the `quantity_index` passed in matches your cached index. If so, do your sauce to compute the quantity and set the variable `value` to the value of your new postprocessed quantity; this is what will be output.

4. Compile and test.

Please let me know if there's anything unclear or if you get stuck. I tried to make this as painless as possible, so I'll be interested if there's any way I can improve it (beyond #175  and #242).

Right now, the postprocessing is only doing a local L2 projection onto a linear basis (there's no input knob for an order). So, if your new quantity is a derivative, it's probably going to be crappy at element boundaries and will be discontinuous across elements. Burning on my todo list is adding gradient-recovery quantities ala Zienkiewicz-Zhu. (Basically averaging derivatives over node patches. This is how stress postprocessing is typically done, for example.)

**Comment by pbauman** [comment]
Looks like this was satisfied awhille back. Ref. discussion in #246.
