### ISSUE TITLE
Pressure pinning *usually* only works near domain sides

### ISSUE THREAD

**Issue by roystgnr** [grinsfem/grins#244]
Because pin_value is called from side_constraint (in all physics except plain Stokes), and because by default FEMSystem only integrates on sides which have no neighbors, pin_value is only called on elements which border the domain boundary.

This is probably a fine restriction to have.  It's what I do in fem_system_ex1.  contains_point() is a little costly, so better to call it O(N^{(d-1)/d}) times than O(N) times.

This is a scary restriction to have, though.  I just wasted an hour or two trying to figure out why I wasn't seeing pressure pinning in a run.  I'm not sure how to get the code to emit a warning in such cases, but that might be worth looking into.

**Comment by pbauman** [comment]
> I just wasted an hour or two trying to figure out why I wasn't seeing pressure pinning in a run. 

Shit, sorry.

> I'm not sure how to get the code to emit a warning in such cases, but that might be worth looking into.

This should be an error. Somewhere in the init stage, we should have pressure pinning check that a valid point was selected.

**Comment by roystgnr** [comment]
Damn it.  @vikramvgarg just wasted *way* more than an hour looking for a sensitivities bug that in the end boiled down to "the solution was floating with pressure unpinned".  I'd say let's just move the pin_value from side_constraint to element_constraint, but that'll just make the class of errors smaller; people could still screw up and pick a pinning point outside the domain too easily.

Could we add a static bool "is_pinned", initialize to false, flip to true when the pinning point is first found, then scream bloody murder in the destructor if it isn't true?  That's still got failure possibilities with mesh movement and element creation/destruction, but it'd catch all our current use cases.

**Comment by pbauman** [comment]
Sorry, this should've been fixed a long time ago. I'll do this first thing when I'm done teaching this morning.
