### ISSUE TITLE
Forcing Source

### ISSUE THREAD

**Issue by nicholasmalaya** [grinsfem/grins#247]
This issue request is to add a forcing function to GRINS. This permits, when specified by the input file, to read a parsed function that will then spatially force the velocity field in some region. 

This is we can be less restricted in terms of manipulating the flow than with the velpenalty.  In particular, to start, the most useful feature will be to add a vertical forcing in a small region near the ground, inside the boundary layer. 

I chatted with Roy about this in the AM, although I am still not totally sure how to implement this guy. It sounds as if we can use a similar infrastructure to the velocity penalty, but now with a simpler structure given that the forcing does not require normal vectors, etc.

**Comment by nicholasmalaya** [comment]
A few questions: 

A) Do we think this might be more generally useful for GRINS users? 
B) Should I instantiate it as a new piece of physics, al la velocity penalty?
C) Obviously forcing like this is not energy conserving, so is there an easy way for someone to calculate the energy introduced by the forcing? I suppose I would need to be able to integrate over a region of forcing.

**Comment by pbauman** [comment]
> Do we think this might be more generally useful for GRINS users? 

Yes. In fact, I've been talking with @cahaynes about generalizing the input of source terms (there's at least 2 in GRINS right now and they're overly specialized). We ought to have a just a generic `SourceTerm` (or something) with `Constant` and `Parsed` versions that looks for the variables to which you're adding the source term and grabs the value/expression for the source term and just adds it to the residual (FE type, etc. would be grabbed from the Variable info).

I was originally thinking we would be running headlong the "Reusing a single `Physics` class in the same simulation problem", but there's no reason we couldn't just have this thing soak up all the source terms in one class (might be nice to have multiples for modularity, but this would be a start).

I'd need to do the Variables-input-refactoring first.

Thoughts?

> C) Obviously forcing like this is not energy conserving, so is there an easy way for someone to calculate the energy introduced by the forcing? I suppose I would need to be able to integrate over a region of forcing.

This sounds kind of specialized. Not sure how I'd want to handle this, but I'm open to suggestions.

**Comment by pbauman** [comment]
#47 was my first expression of regret along these lines.

**Comment by nicholasmalaya** [comment]
I'm afraid I'm going to need this capability sooner rather than later. I'm guessing this means I should just plan on creating a new physics class (with the associated variable name caching and initing the variable indices, etc.) and that can be reduced down in a refactor at a later date?

Alternatively, I'm wondering if the easiest option might not be to create a branch where we write over a source term that we want instead of an existing one. This requires that we have an existing source term that exists in GRINS but is not presently in use for the SoV... if this is the case could you point me towards it?

If we can do the latter I'm still happy to help with the general refactor, but this would be better because that could then be done at a more leisurely pace.

**Comment by nicholasmalaya** [comment]
My needs appear to be completely covered in #251 Closing this issue, would mark as complete if github let me...
