### ISSUE TITLE
tag and bag a release

### ISSUE THREAD

**Issue by nicholasmalaya** [grinsfem/grins#283]
We have reached an equilibrium in terms of SoV GRINS development. I'm inclined to recommend we tag a release so we have this one for longevity. 

It appears to me that the appropriate hash is around: https://github.com/grinsfem/grins/commit/d4ca6f31898661f113705ecd6499263b32ab6668

which was on Apr 20, 2015. That includes everything (I believe) that I am presently using, and we should be good with this for another month or so, possibly longer.

**Comment by pbauman** [comment]
This seems reasonable to me. I'm kind of deep in a stack that I'll (hopefully...) be unwinding shortly, so if you guys are running stable, this is a good as place as any to tag.

Just for my reference, for updating change log, need to look back to 1a6c07be073a02c47c4f922a19b514b5d79c6bd9

**Comment by nicholasmalaya** [comment]
I don't think I am capable (in terms of permission) to tag a release on github-- anything I can do to help set this up to occur? 

I am not in a rush, but I would like ensure this does happen, since it is an important milestone to have archived long term.

**Comment by pbauman** [comment]
Apologies @nicholasmalaya. I'm under a deadline - once I've saturated the supercomputer queue, I'll tag a release. Either today or tomorrow.

**Comment by pbauman** [comment]
One helpful thing, if you've got nothing better to do, is start identifying existing warnings to clean up and hitting `make distcheck`.
