### ISSUE TITLE
Missing data file in sa_airfoil example

### ISSUE THREAD

**Issue by pbauman** [grinsfem/grins#321]
Looks like the restart was hardcoded to a path on @vikramvgarg's computer. @vikramvgarg do you have the restart file associated with this example?

**Comment by vikramvgarg** [comment]
Can I email it to you or should I make a PR ?

On Fri, Oct 9, 2015 at 9:20 PM, Paul T. Bauman <notifications@github.com>
wrote:

> Looks like the restart was hardcoded to a path on @vikramvgarg
> <https://github.com/vikramvgarg>'s computer. @vikramvgarg
> <https://github.com/vikramvgarg> do you have the restart file associated
> with this example?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grinsfem/grins/issues/321>.
>



-- 
Vikram Garg
Postdoctoral Associate
Predictive Engineering and Computational Science (PECOS)
The University of Texas at Austin
http://web.mit.edu/vikramvg/www/

http://vikramvgarg.wordpress.com/
http://www.runforindia.org/runners/vikramg

**Comment by pbauman** [comment]
Email is fine

**Comment by pbauman** [comment]
Fixed this in 4613c83.
