### ISSUE TITLE
Error estimator failing assert `error_per_cell[i] >= 0'

### ISSUE THREAD

**Issue by vikramvgarg** [grinsfem/grins#346]
When I used the adjoint refinement error estimator, I get the following output:

Checking convergence

Error estimate = -0.0322016

Performing Mesh Refinement

Assertion `error_per_cell[i] >= 0' failed.
error_per_cell[i] = -1.7749e-11
0 = 0

The adjoint refinement estimator computes cell wise errors from localized residuals. The user is supposed to take the error vector from adjoint refinement estimator, take absolute values per element and use that for flagging.

Should we check for the use of ADJOINT_REFINEMENT in MeshAdaptiveSolverBase::perform_amr and take absolute values of the error vector there ?

**Comment by roystgnr** [comment]
Hmm... what we really ought to be doing is taking the absolute value in libMesh, around line 423 of adjoint_refinement_error_estimator.C - switch the libmesh_real() conversion to be std::abs() and see if that fixes it?

DAMN.  This would explain @pbauman's observation that ARefEE performs much worse than AResEE as a refinement indicator...

**Comment by vikramvgarg** [comment]
Yes, that seems to have fixed the problem. Have created a pull request.

On Tue, Feb 2, 2016 at 7:07 PM, roystgnr <notifications@github.com> wrote:

> Hmm... what we really ought to be doing is taking the absolute value in
> libMesh, around line 423 of adjoint_refinement_error_estimator.C - switch
> the libmesh_real() conversion to be std::abs() and see if that fixes it?
>
> DAMN. This would explain @pbauman <https://github.com/pbauman>'s
> observation that ARefEE performs much worse than AResEE as a refinement
> indicator...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grinsfem/grins/issues/346#issuecomment-178932024>.
>



-- 
Vikram Garg
Postdoctoral Associate
Predictive Engineering and Computational Science (PECOS)
The University of Texas at Austin
http://web.mit.edu/vikramvg/www/

http://vikramvgarg.wordpress.com/
http://www.runforindia.org/runners/vikramg

**Comment by pbauman** [comment]
> This would explain @pbauman's observation that ARefEE performs much worse than AResEE as a refinement indicator...

It could, but I'm skeptical. I'll give it a whirl in the next couple of weeks.

**Comment by pbauman** [comment]
Closing since this is addressed in libMesh/libmesh#818
