### ISSUE TITLE
autoreconf error on Ls5

### ISSUE THREAD

**Issue by nicholasmalaya** [grinsfem/grins#353]
Here is the error, discussion below:
<pre>
login2.ls5(20)$ ./bootstrap 
Bootstrapping using autoreconf -v -f -i ...
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4 -I m4/common
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
/opt/apps/autotools/1.1/bin/libtoolize: line 406: /root/bin/sed: Permission denied
/opt/apps/autotools/1.1/bin/libtoolize: line 2513: /root/bin/sed: Permission denied
/opt/apps/autotools/1.1/bin/libtoolize: line 2513: /root/bin/sed: Permission denied
/opt/apps/autotools/1.1/bin/libtoolize: line 3601: /root/bin/sed: Permission denied
/opt/apps/autotools/1.1/bin/libtoolize: line 3845: /root/bin/sed: Permission denied
/opt/apps/autotools/1.1/bin/libtoolize: line 861: /root/bin/sed: Permission denied
: putting auxiliary files in '.'.
: copying file './ltmain.sh'
/opt/apps/autotools/1.1/bin/libtoolize: line 3771: /root/bin/sed: Permission denied
autoreconf: running: /opt/apps/autotools/1.1/bin/autoconf --force
autoreconf: running: /opt/apps/autotools/1.1/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:17: error: required file 'build-aux/ltmain.sh' not found
autoreconf: automake failed with exit status: 1
</pre>

It looks to be as if autoreconf is grabbing the wrong 'sed' (in fact, one that does not exist),
<pre>
login2.ls5(25)$ ls /root/bin/sed
ls: cannot access /root/bin/sed: Permission denied
</pre>

When I have a perfectly happy sed sitting in,
<pre>
login2.ls5(26)$ which sed
/usr/bin/sed
</pre>

This is confirmed with a fresh check out of GRINS. Scarily, it will give you a configure and will be more than happy to build, but thinks get borked after that due to the lack of several makefile.in

So my question is: how can I manually set generated configuration files, in this case, to point at the correct path to the tool 'sed'? This is a weird error I have not seen before...

**Comment by pbauman** [comment]
This is odd. I'm guessing that the autotools were built using the the `/root/bin/sed` and read permission isn't being granted. I don't see any knobs in `autoreconf` to reset this. I'd send this error to the `ls5` maintainers and ask what's up with their autotools installation.

**Comment by nicholasmalaya** [comment]
Ack, I bet you are right. In fact, you must be at least partially correct as Libmesh *did* build and it likely built its own autotools suite. I just ping'ed TACC, will update this ticket when things work but I'm not being blocked by GRINS at present.

**Comment by nicholasmalaya** [comment]
TACC's rebuild is at least now resulting in an error-free configure. All indications point to GRINS successfully building and functioning on LS5 with intel 16.0. I'm closing this ticket.
