### ISSUE TITLE
Deprecated libmesh_common.h

### ISSUE THREAD

**Issue by tradowsk** [grinsfem/grins#439]
Per @pbauman's request

*** Warning, This code is deprecated, and likely to be removed in future library versions! /.../libmesh/.../include/libmesh/libmesh_common.h, line 497

which is `libmesh_cast_ref()`

**Comment by pbauman** [comment]
Context for future me: Looks like we (GRINS) is using the deprecated libmesh_cast_ref() in places. Let's get rid of them.
