### ISSUE TITLE
suspended_cable_test.sh fails in parallel

### ISSUE THREAD

**Issue by roystgnr** [grinsfem/grins#447]
It breaks even on 2 processors for me.  I can't seem to get it to converge reliably in parallel without MUMPS LU.

**Comment by pbauman** [comment]
Damn. That shouldn't be happening. I'll take a look, hopefully tonight, to see how changes effected this. REALLY REALLY wanting Civet to be open-sourced... Might be time to just suck it up and try and get BuildBot working.
