### ISSUE TITLE
GRINS master doesn't build for me with clang 3.9.0

### ISSUE THREAD

**Issue by jwpeterson** [grinsfem/grins#510]
I googled this error a bit but don't know exactly how to fix it yet... Do you guys ever build with clang?

```
boundary_conditions/src/catalycity_factory_abstract.C:41:52: error: explicit specialization of '_input' after instantiation
  const GetPot* FactoryWithGetPot<CatalycityBase>::_input = NULL;
                                                   ^
../src/boundary_conditions/include/grins/catalycity_factory_abstract.h:69:82: note: implicit instantiation first required here
    libMesh::UniquePtr<CatalycityBase> new_catalycity = this->build_catalycity( *_input, _section );
                                                                                 ^
```

**Comment by roystgnr** [comment]
I haven't built GRINS with clang, but I believe I recognize this bug - you have to have a declaration of the specialization which *precedes* automatic instantiation.  Maybe try putting
```
template<>
const GetPot* FactoryWithGetPot<CatalycityBase>::_input;
```
in catalycity_factory_abstract.h before the CatalycityFactoryAbstract definition?

Kind of weird that that's being specialized, though... @pbauman, did you really intend to have a different static GetPot pointer for this particular factory instantiation?

**Comment by jwpeterson** [comment]
I *think* your fix worked, but there seem to be several other similar issues which can probably be fixed with related declarations:
```
../../src/boundary_conditions/src/neumann_bc_factory_abstract.C:85:56: error: explicit specialization of '_input' after instantiation
  const GetPot* FactoryWithGetPot<NeumannBCContainer>::_input = NULL;
                                                       ^
../../src/boundary_conditions/src/neumann_bc_factory_abstract.C:45:45: note: implicit instantiation first required here
          func = this->build_neumann_func( *_input, *_system, *_fe_var, this->_section );
                                            ^
../../src/boundary_conditions/src/neumann_bc_factory_abstract.C:88:62: error: explicit specialization of '_system' after instantiation
  MultiphysicsSystem* BCFactoryAbstract<NeumannBCContainer>::_system = NULL;
                                                             ^
../../src/boundary_conditions/src/neumann_bc_factory_abstract.C:45:54: note: implicit instantiation first required here
          func = this->build_neumann_func( *_input, *_system, *_fe_var, this->_section );
                                                     ^
../../src/boundary_conditions/src/neumann_bc_factory_abstract.C:91:70: error: explicit specialization of '_bc_ids' after instantiation
  const std::set<BoundaryID>* BCFactoryAbstract<NeumannBCContainer>::_bc_ids = NULL;
                                                                     ^
../../src/boundary_conditions/src/neumann_bc_factory_abstract.C:49:49: note: implicit instantiation first required here
        container.reset(new NeumannBCContainer(*_bc_ids,*_fe_var,func));
                                                ^
../../src/boundary_conditions/src/neumann_bc_factory_abstract.C:94:65: error: explicit specialization of '_fe_var' after instantiation
  const FEVariablesBase* BCFactoryAbstract<NeumannBCContainer>::_fe_var = NULL;
                                                                ^
../../src/boundary_conditions/src/neumann_bc_factory_abstract.C:45:64: note: implicit instantiation first required here
          func = this->build_neumann_func( *_input, *_system, *_fe_var, this->_section );
                                                               ^
../../src/boundary_conditions/src/neumann_bc_factory_abstract.C:97:54: error: explicit specialization of '_section' after instantiation
  std::string BCFactoryAbstract<NeumannBCContainer>::_section = std::string("DIE!");
                                                     ^
../../src/boundary_conditions/src/neumann_bc_factory_abstract.C:45:79: note: implicit instantiation first required here
          func = this->build_neumann_func( *_input, *_system, *_fe_var, this->_section );
                                                                              ^
```

**Comment by pbauman** [comment]
> Kind of weird that that's being specialized, though... @pbauman, did you really intend to have a different static GetPot pointer for this particular factory instantiation?

No, but I must not fully understand (or have understood when this was written) how static members of template classes work. The base class is templated and I thought I was required to instantiate that static member for each subclass for each of the instantiated templates (which was very annoying). Please tell me how I'm wrong. Also, yes, I didn't know that I would be required to have this declaration?(I have the initialization in the .C file). How has 3 major releases of GCC not errored on this?

**Comment by roystgnr** [comment]
> Please tell me how I'm wrong.

You're right!  However, that's only applicable if what you really want is a separate static member for each template specialization.  If you want a single static member that's shared between all specializations, you can create a non-templated base-of-the-base class, put the static member in *that* superclass, and then have the templated class inherit from it.  Then only one member exists and only one initialization is needed.

> Also, yes, I didn't know that I would be required to have this declaration?(I have the initialization in the .C file). How has 3 major releases of GCC not errored on this?

I'm honestly not sure whether this is an error according to the standard or whether this is a clang bug.  It *looks* similar to erroneous code I've written (where you have a specialization of a templated function, but you don't declare that specialization until after you accidentially instantiate the non-specialized function), but in this case there's no *specialization* in our specialization, just manual instantiation, so I'm not sure why clang can't or won't consider the declaration in factory_with_getpot.h to be sufficient.
