### ISSUE TITLE
Output test failures in Civet recipe?

### ISSUE THREAD

**Issue by roystgnr** [grinsfem/grins#537]
https://femputer.eng.buffalo.edu:8000/job/1405/ shows a failure at ```make -j 8 check```, but I can't yet replicate that failure locally.  Could we replace that Civet test command with something like ```make -j 8 check || (cat test/test_suite.log; false)``` in case that happens again?

And in this particular case, could you let me know what the failure was?  ;-)  Presumably it was a ReplicatedMesh failure that doesn't break on DistributedMesh, so I'll try a build like that next, but it'd be good to have more information in case my hunch is wrong.

**Comment by pbauman** [comment]
Well, the CIVET page says it's np 4 but I'm guess I'm running it with np 8. *sigh* I'll at least drop that simple cat command in, it will be overly verbose, but that's better than nothing at all.

**Comment by pbauman** [comment]
OK, I added `|| (cat test/test-suite.log; false)` to the check commands for both libMesh and GRINS make check shell scripts. They should be live *right now*.  Will also submit a fake PR where some tests should fail to test this to be extra extra sure we don't have any false passes, i.e. green when it should be red on CIVET.

**Comment by pbauman** [comment]
> Well, the CIVET page says it's np 4 but I'm guess I'm running it with np 8.

And I'm still not firing on all cylinders with this illness. There's 8 make threads running `mpiexec -np 4` as it should be. If I'm not careful, someone is going to take the keyboard away from me soon...

**Comment by pbauman** [comment]
OK, will let CIVET run it's course, but looks like it's working (even though for some reason the CIVET shell function is not echoing the part after `make -j 32 check`, but it's cat'ing the test log.

**Comment by pbauman** [comment]
OK, everything seems to be working as expected. Sorry I haven't had more time to devote to creating a script that cat's only the tests that failed. But too much information is better than none.

**Comment by roystgnr** [comment]
> Sorry I haven't had more time to devote to creating a script that cat's only the tests that failed. But too much information is better than none.

Honestly, I prefer it this way.  I've had tests fail before because I accidentally duplicated an output file name and they stomped on each others toes.  Test failures *should* have nothing to do with other tests' successes, but it doesn't always work that way.

**Comment by pbauman** [comment]
> I've had tests fail before because I accidentally duplicated an output file name and they stomped on each others toes.

There were a couple of those heisenbugs going around in the GRINS test suite too, but I thought I'd squashed all of them, but that recent parsed_qoi test failure makes me think otherwise...
