### ISSUE TITLE
Make check failing with antioch/cantera

### ISSUE THREAD

**Issue by tradowsk** [grinsfem/grins#545]
Compiled with GRINS master and current Antioch master 7cebf19 (Cantera not included).

Relevant portion of test-suite.log

```
==========================================================
WARNING: Specifying boundary conditions in the
         Physics sections is DEPRECATED! Please
         update your input file to new the newer
         style. See the examples for an illustration.
../../src/src/boundary_conditions/src/old_style_bc_builder.C, line 59, compiled Apr 19 2018 at 09:51:08 ***
==========================================================
xxx/software/fem/build/test/.libs/lt-unit_driver: symbol lookup error: xxx/software/fem/build/test/.libs/lt-unit_driver: undefined symbol: _ZN5GRINS24OverlappingFluidSolidMapC1ERNS_18MultiphysicsSystemERKN7libMesh16PointLocatorBaseERKSt3setItSt4lessItESaItEESD_RKNS_20DisplacementVariableE
FAIL unit_driver (exit status: 127)
```

Also compiled with both Antioch master and Cantera 2.2.0 and failed 6 tests:

```
FAIL: unit/gas_recombination_catalytic_wall_cantera.sh
FAIL: unit/cantera_mixture.sh
FAIL: interface/cantera_transport_regression.sh
....
FAIL: interface_driver
FAIL: unit/gas_solid_catalytic_wall_cantera.sh
...
FAIL: unit_driver
```

**Comment by pbauman** [comment]
I didn't even think we could compile with Cantera > 2.1.2 (which is what I've been using for awhile). OK, thanks, will take a look at these tonight.

**Comment by tradowsk** [comment]
FYI I also get the same 6 failures when using Cantera/2.1.2

**Comment by pbauman** [comment]
Chatting with @tradowsk in meatspace, it looks like it was an `LD_LIBRARY_PATH` issue on his side. However, there may still be issues with Antioch enabled and not Cantera or vice-versa since that hasn't been tested by me ever or by CI. So will keep this open in case that's an issue.

**Comment by tradowsk** [comment]
Issue was with my `LD_LIBRARY_PATH` not GRINS itself

**Comment by tradowsk** [comment]
I made my comment like 30 minutes ago, don't know why it didn't show up until after @pbauman's...

Anyway, reopening based on above comment

**Comment by pbauman** [comment]
Just did a master build with Antioch on, Cantera off and vice-versa and everything was good. Closing this.
