### ISSUE TITLE
Vector conversion error

### ISSUE THREAD

**Issue by ehsanakrami** [grinsfem/grins#600]
https://github.com/grinsfem/grins/blob/3c4e2ae2c7f053a41a5e99993049d797046e87e0/src/utilities/src/distance_function.C#L640

It seems that this line needs an amendment to:
```std::vector<long unsigned int> dof_ind;```

**Comment by pbauman** [comment]
Hi @ehsanakrami I'm not sure I follow. What amendment do you think is needed? I might anticipate you mean that the vector needs to be sized, but the `dof_indices` call on the next line will `clear()` and `insert` into that vector so no explicit sizing/initialization is needed.

**Comment by ehsanakrami** [comment]
Hi @pbauman. I have updated my comment. Sorry if it was not clear at first.

**Comment by roystgnr** [comment]
That ought to be dof_id_type, right?  Not hard-coded to unsigned int *or* unsigned long, since libMesh could be configured to use either?

**Comment by ehsanakrami** [comment]
Hi, Unfortunately, my libMesh couldn't and I amend it by myself to compile.

**Comment by roystgnr** [comment]
Fixed by #604
