### ISSUE TITLE
Fix configuring against OpenMP-enabled libMesh

### ISSUE THREAD

**Issue by roystgnr** [grinsfem/grins#82]
On stampede, I have to set "CXXFLAGS=-fopenmp" on my configure line; otherwise the attempt in libmesh_new.m4 to test linking against libMesh fails with undefined symbols.  And although using this workaround is easy, *figuring out* this workaround was hell I don't want anyone else to go through.

Ironically, that flag is set by default in the libMesh CXXFLAGS, and we *use* the libMesh CXXFLAGS by default, but we don't actually query those flags until *outside* the test for libMesh.

I *think* the right fix here is to use the libMesh CXXFLAGS in the test inside libmesh_new.m4; but other thoughts are welcome.

**Comment by pbauman** [comment]
This should be fixed by #370.
